### ISSUE TITLE
problem setting up jekyll

### ISSUE THREAD

**Issue by childers** [i5k/i5k.github.io#3]
I had Jekyll up and running, and when I ran `git pull`  Jekyll dies with a new error.  Anyone else seeing this?

``` shell
$ jekyll 
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source': uninitialized constant Gem::Source (NameError)
Did you mean?  Gem::Source
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:46:in `gem_build_complete_path'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2174:in `missing_extensions?'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1082:in `block (2 levels) in find_in_unresolved_tree'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2621:in `block (2 levels) in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `block in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2627:in `block (2 levels) in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `block in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1078:in `block in find_in_unresolved_tree'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1077:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1077:in `find_in_unresolved_tree'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:86:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:46:in `gem_build_complete_path'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2174:in `missing_extensions?'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1082:in `block (2 levels) in find_in_unresolved_tree'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2621:in `block (2 levels) in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `block in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2627:in `block (2 levels) in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2616:in `block in traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2614:in `traverse'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1078:in `block in find_in_unresolved_tree'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1077:in `each'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1077:in `find_in_unresolved_tree'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:86:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.0/lib/bundler/rubygems_integration.rb:2:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.0/lib/bundler.rb:11:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/plugin_manager.rb:32:in `require_from_bundler'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/bin/jekyll:9:in `<top (required)>'
    from /usr/local/bin/jekyll:22:in `load'
    from /usr/local/bin/jekyll:22:in `<main>'
```

**Comment by childers** [comment]
Apparently I had some conflicting gems installed. Running `bundle clean --force` seems to have solved the issue.

**Comment by monicacecilia** [comment]
I like this kind of self-solving dialogs. :bowtie:

**Comment by childers** [comment]
Unfortunately, the solutions the Google gave me were not helpful in the end.  I'm just glad I could suss out what was going on.
